version: 2.1

orbs:
  gor: hubci/goreleaser@1.0
  osd: circleci/os-detect@0.3.0

executors:
  linux-docker:
    docker:
      - image: cimg/base:2022.01
  linux-amd64:
    machine:
      image: ubuntu-2004:202111-02
  linux-arm64:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium
  macos:
    macos:
      xcode: 12.3.0
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.medium

workflows:
  main:
    jobs:
      - test
      - gor/release:
          version: "1.4.1"
          go-version: "1.17.6"
          dry-run: true
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
      - test-with-images:
          requires:
            - gor/release
          matrix:
            parameters:
              image:
                - linux-docker
                - linux-amd64
                - linux-arm64
                - macos
                #- windows
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: "1.4.1"
          go-version: "1.17.6"
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
          context: main

jobs:
  test:
    docker:
      - image: cimg/go:1.17.6
    environment:
      GOTESTSUM_JUNITFILE: "junit/unit-tests.xml"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: "Download Dependancies"
          command: cd valerie && go mod download
      - run:
          name: "Run Tests & Coverage"
          command: |
            cd ./valerie
            mkdir junit
            gotestsum -- -coverprofile=coverage.txt -covermode=atomic ./...
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit/unit-tests.xml
      - run:
          name: "Upload to Codecov"
          command: cd valerie && bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/.cache/go-build"
  test-with-images:
    parameters:
      image:
        type: executor
    executor: <<parameters.image>>
    steps:
      - osd/init
      - attach_workspace:
          at: .
      - run: |
          if [ $OSD_FAMILY == "linux" ]; then
            ./dist/valerie_linux_$(dpkg --print-architecture)/valerie version
          else
            ./dist/valerie_darwin_amd64/valerie version
          fi
